//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mq.model.dbentity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BG_ChangeUserPosition
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public long OldAreaId { get; set; }
        public long OldShopId { get; set; }
        public long NewAreaId { get; set; }
        public long NewShopId { get; set; }
        public System.DateTime AddTime { get; set; }
        public int IsDel { get; set; }
        public long PassUserId { get; set; }
        public string PassUserName { get; set; }
        public Nullable<System.DateTime> PassDateTime { get; set; }
        public int Status { get; set; }
    }
}
