//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mq.model.dbentity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BG_Position
    {
        public long PositionId { get; set; }
        public long DepartmentId { get; set; }
        public long Lvl { get; set; }
        public System.DateTime AddTime { get; set; }
        public Nullable<long> IsDel { get; set; }
        public string PositionName { get; set; }
    }
}
